#pragma once
#include "Utils/HostDeviceShared.slangh"

BEGIN_NAMESPACE_FALCOR

enum class ShiftMappingType : uint32_t
{
    Reconnection = 0,
    Hybrid = 1,
};

FALCOR_ENUM_INFO(ShiftMappingType, {
    { ShiftMappingType::Reconnection, "Reconnection" },
    { ShiftMappingType::Hybrid, "Hybrid" },
});
FALCOR_ENUM_REGISTER(ShiftMappingType);

/** A struct to store info needed to reconstruct a hit for reconnection shifts
 */
struct RCVertex
{
    float3 outgoingDir; // outgoing w_o from reconnection vert x_k
    float outgoingPdf; // pdf of sampling outgoingDir
    float3 incomingRadiance; // L incoming at x_k, along rcOutgoingDir
    uint4 packedHitInfo; ///< Packed hit info for reconnection vertex
    uint prevSampledLobeType; //will be a LobeType uint, representing which lobe type got sampled for vert x_(k-1)
    uint sampledLobeType; //LobeType uint, representing lobe type sampled for vert x_k

    #ifndef HOST_CODE
    __init(){
        outgoingDir = {0.f, 0.f, 0.f};
        outgoingPdf = 0.f;
        incomingRadiance = {0.f, 0.f, 0.f};
        packedHitInfo = {0, 0, 0, 0};
        prevSampledLobeType = 0;
        sampledLobeType = 0;
    }

    __init(float3 wo, float pdf, float3 Li, uint4 packedHit, uint prevLobeType, uint curLobeType){
        outgoingDir = wo;
        outgoingPdf = pdf;
        incomingRadiance = Li;
        packedHitInfo = packedHit;
        prevSampledLobeType = prevLobeType;
        sampledLobeType = curLobeType;
    }
    #endif
};

/** Types of samplable lights. Named changed from LightType to avoid confusion with the analytic light types in LightHelpers
 */
enum class NEELightType
{
    EnvMap,
    Emissive,
    Analytic
};

/** Describes a light sample.
 */
struct LightSample
{
    float3 Li;      ///< Incident radiance at the shading point (unshadowed). This is already divided by the pdf.
    float pdf;      ///< Pdf with respect to solid angle at the shading point.
    float3 origin;  ///< Ray origin for visibility evaluation (offseted to avoid self-intersection).
    float distance; ///< Ray distance for visibility evaluation (shortened to avoid self-intersection).
    float3 dir;     ///< Ray direction for visibility evaluation (normalized).
    uint lightType; ///< Light type this sample comes from (LightType casted to uint).
    float g = 0; ///< Geometry term for the light sample, only valid if the light sample is from an emissive triangle
};

/** Convenience struct for holding info about the uints needed to seed a SampleGenerator.
 */
struct PRNGSeed
{
    uint2 pixel;
    uint sampleNumber;

    #ifndef HOST_CODE

    __init(){
        pixel = uint2(0, 0);
        sampleNumber = 0;
    }

    __init(uint2 pix, uint sampleNum){
        pixel = pix;
        sampleNumber = sampleNum;
    }

    #endif
};

/**
 Describes a path as a sequence of vertices, used by the PathViewer
*/
struct PathViewerPath
{
    uint numNonCameraVertices; // the same as the index of the last vertex on this path
    uint rcIndex; // ex for reconnection shift this will be 2
    float3 vertices[5]; // starts at x1, then x2, x3, etc since camera pos is determined. these are the ray origins NOT sd.posW

    #ifndef HOST_CODE
    
    __init(uint numVerts, uint rci){
        numNonCameraVertices = numVerts;
        rcIndex = rci;
        for(int i = 0; i < 5; i++){
            vertices[i] = float3(0.f);
        }
    }

    #endif
};

END_NAMESPACE_FALCOR
