#pragma once
#include "Utils/HostDeviceShared.slangh"

BEGIN_NAMESPACE_FALCOR

enum class ShiftMappingType : uint32_t
{
    Reconnection = 0,
    Hybrid = 1,
};

FALCOR_ENUM_INFO(ShiftMappingType, {
    { ShiftMappingType::Reconnection, "Reconnection" },
    { ShiftMappingType::Hybrid, "Hybrid" },
});
FALCOR_ENUM_REGISTER(ShiftMappingType);

/** A struct to store info needed to reconstruct a hit for reconnection shifts
 */
struct RCVertex
{
    float3 outgoingDir; // outgoing w_o from reconnection vert x_k
    float3 incomingRadiance; // L incoming at x_k, along rcOutgoingDir
    uint4 packedHitInfo; ///< Packed hit info for reconnection vertex
    uint prevSampledLobeType; //will be a LobeType uint, representing which lobe type got sampled for vert x_(k-1)
    uint sampledLobeType; //LobeType uint, representing lobe type sampled for vert x_k

    #ifndef HOST_CODE
    __init(){
        outgoingDir = {0.f, 0.f, 0.f};
        incomingRadiance = {0.f, 0.f, 0.f};
        packedHitInfo = {0, 0, 0, 0};
        prevSampledLobeType = 0;
        sampledLobeType = 0;
    }

    __init(float3 wo, float3 Li, uint4 packedHit, uint prevLobeType, uint curLobeType){
        outgoingDir = wo;
        incomingRadiance = Li;
        packedHitInfo = packedHit;
        prevSampledLobeType = prevLobeType;
        sampledLobeType = curLobeType;
    }
    #endif
};

/** Types of samplable lights. Named changed from LightType to avoid confusion with the analytic light types in LightHelpers
 */
enum class NEELightType
{
    EnvMap,
    Emissive,
    Analytic
};

/** Describes a light sample.
 */
struct LightSample
{
    float3 Li;      ///< Incident radiance at the shading point (unshadowed). This is already divided by the pdf.
    float pdf;      ///< Pdf with respect to solid angle at the shading point.
    float3 origin;  ///< Ray origin for visibility evaluation (offseted to avoid self-intersection).
    float distance; ///< Ray distance for visibility evaluation (shortened to avoid self-intersection).
    float3 dir;     ///< Ray direction for visibility evaluation (normalized).
    uint lightType; ///< Light type this sample comes from (LightType casted to uint).
    float g = 0; ///< Geometry term for the light sample, only valid if the light sample is from an emissive triangle
};

/** Describes a path vertex.
 */
struct PathVertex
{
    uint index;        ///< Vertex index (0 = camera, 1 = primary hit, 2 = secondary hit, etc.).
    float3 pos;        ///< Vertex position.
    float3 faceNormal; ///< Geometry normal at the vertex (zero if not on a surface).
    bool frontFacing;  ///< True if path vertex is on the front-facing side (if on a surface).

    #ifndef HOST_CODE //this excludes functions that change the state of the struct from being seen by c++ compiler

    /** Initializes a path vertex.
        \param[in] index Vertex index.
        \param[in] pos Vertex position.
        \param[in] faceNormal Geometry normal.
        \param[in] frontFacing Front-facing flag.
    */
    __init(uint index, float3 pos, float3 faceNormal = float3(0.f), bool frontFacing = true)
    {
        this.index = index;
        this.pos = pos;
        this.faceNormal = faceNormal;
        this.frontFacing = frontFacing;
    }
    static PathVertex NULL = { -1, float3(0.f), float3(0.f), false };

    /** Get position with offset applied in direction of the geometry normal to avoid self-intersection
        for visibility rays.
        \param[in] rayDir Direction of the visibility ray (does not need to be normalized).
        \return Returns the offseted position.
    */
    float3 getRayOrigin(float3 rayDir)
    {
        return computeRayOrigin(pos, dot(faceNormal, rayDir) >= 0 ? faceNormal : -faceNormal);
    }

    /** Returns the oriented face normal.
        \return Face normal flipped to the same side as the view vector.
    */
    float3 getOrientedFaceNormal()
    {
        return frontFacing ? faceNormal : -faceNormal;
    }
    #endif
};

END_NAMESPACE_FALCOR
